### ISSUE TITLE
AssertionError: The render_mode must be 'rgb_array', not None

### ISSUE THREAD

**Issue by ziyao-hhs** [ScheiklP/sofa_zoo#1]
HI, when I execute `python3 reach/ppo.py`, I received an error says 
![image](https://github.com/ScheiklP/sofa_zoo/assets/68358818/59ee4056-279c-42a8-a881-ff8721d1838b)
can I do anything to solve this?

**Comment by ScheiklP** [comment]
Hi @ziyao-hhs,
in the newest release, stable-baselines has changed over to gymnasium in favor of gym.

I will change the required version of stable-baselines in setup.py to version v1.8.0, until I also migrate sofa_env and sofa_zoo to gymnasium.

Let me know, if that solves your issue.

Cheers,
Paul

**Comment by saketh2002** [comment]
getting this issue after trying with main branch, gynamisum is installed

**Comment by ScheiklP** [comment]
Hi @saketh2002,
sadly I currently do not have a system on which to test this.

Could you please open a new issue?
I will try to give it a look in September. 

Best,
Paul

**Comment by saketh2002** [comment]
Yeah, will actually mention the issue elaborately over there
