### ISSUE TITLE
Precision Cutting TypeError

### ISSUE THREAD

**Issue by kanta-lee** [ScheiklP/sofa_zoo#11]
When I tried to run `ppo.py` for precision cutting, I encountered a TypeError.

```
[ERROR]   [PythonScript] TypeError: 'tuple' object does not support item assignment
  File "/bd_targaryen/users/kleelakunwet/sofa_zoo/sofa_zoo/envs/precision_cutting/ppo.py", line 136, in <module>
    model.learn(
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 315, in learn
    return super().learn(
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 277, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 194, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 206, in step
    return self.step_wait()
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_frame_stack.py", line 33, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_normalize.py", line 181, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 88, in step_wait
    obs, rews, dones, infos = self.venv.step_wait()
  File "/bd_targaryen/users/kleelakunwet/miniconda3/envs/sofa/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_monitor.py", line 76, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "/bd_targaryen/users/kleelakunwet/sofa_zoo/sofa_zoo/common/reset_process_vec_env.py", line 110, in step_wait
    obs[i], self.reset_infos[i] = remote.recv()  # collect reset observation
```

I think the reason might come from the return of `zip` function to `self.reset_infos` since the return is the iteration of tuple, which is immutable. The error occurred at line 110 in /sofa_zoo/sofa_zoo/common/reset_process_vec_env.py

<img width="1195" alt="image" src="https://github.com/ScheiklP/sofa_zoo/assets/140193594/bb2b75c6-9f07-49a9-b67f-ab3af56eb29c">

Do you know any other cause of this problem? Thank you in advance!

**Comment by kanta-lee** [comment]
There are also a bunch of other error like invalid triangleS2D size, and pointS2D size.

<img width="1195" alt="image" src="https://github.com/ScheiklP/sofa_zoo/assets/140193594/2ea804bb-050b-4ed9-b663-02c65965c10b">

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
i fixed that bug in this commit https://github.com/ScheiklP/sofa_zoo/commit/708c8f29afb45c3d22c49dd90ffe5afc0178369a.
Could you update your local repository and try again? :)

Cheers,
Paul

**Comment by kanta-lee** [comment]
Hi, @ScheiklP Thanks a lot!
What about the ERROR of `Invalid triangleS2D size` and others? Or the ERROR doesn't harm anything?

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
I have not seen this error before.
Could you give me some more information about your setup?
What are your github commits of
- SOFA
- SofaPython3
- sofa_env
- sofa_zoo
?

Cheers,
Paul

**Comment by kanta-lee** [comment]
@ScheiklP , Is there any command to check those version?

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
in the respective directories, run the command `git log -1`.
```
FOLDER_SRC=$HOME/sofa/src
FOLDER_SP3=$FOLDER_SRC/applications/plugins/SofaPython3
```
and wherever you cloned sofa_env and sofa_zoo.

Cheers,
Paul

**Comment by kanta-lee** [comment]
Got it. Thanks! Below are the commits.

SOFA: cfaeadccb418337c48d63e05adbf7d09e412d375 (FOLDER_SRC)
SofaPython3: b5e28c15305cb8cc21a7dc04d51db47730962f61 (FOLDER_SP3)
sofa_env: 0621d12bad12c496b4efa3070cb86eaa5e006582
sofa_zoo: 708c8f29afb45c3d22c49dd90ffe5afc0178369a

**Comment by ScheiklP** [comment]
Could you update the repositories to the following commits?
SOFA: v23.12 (so just `git checkout v23.12`)
SofaPython3: f1ac0f03efd6f6e7c30df8b18259e16da523f0b2
sofa_env: 3c496f109955d7b2608091e26960db95f996b6d4

**Comment by kanta-lee** [comment]
I can successfully checkout SOFA and SofaPython3, but sofa_env report an error saying that `fatal: reference is not a tree: 3c496f109955d7b2608091e26960db95f996b6d4`

**Comment by ScheiklP** [comment]
Please do a `git fetch` before trying to checkout the commit.

**Comment by kanta-lee** [comment]
<img width="1440" alt="image" src="https://github.com/ScheiklP/sofa_zoo/assets/140193594/515a8b5b-5a37-484f-b0b5-14c2f6f936d5">

I found this error while running just now. It seems like in `sofa_env/scenes/precision_cutting/precision_cutting_env.py`, at line 382, the number of arguments is 2, but 3 is expected. Should I add `rng=self.rng`?

The Invalid thing is still there T.T

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
Two problems:
1. The rng bug was already fixed in commit 830d677e785d54f8e33001d9b35e35db43ec17cb of sofa_env, which is 2 commits before the one you should have checked out.

```
commit 3c496f109955d7b2608091e26960db95f996b6d4 (HEAD -> main, origin/main, origin/HEAD)
Author: Paul Maria Scheikl <paul.m.scheikl@fau.de>
Date:   Fri Mar 15 15:31:24 2024 +0100

    [Docs] Update installation instructions.
```
2. You have to recompile SOFA, so that the binary is up to date with the updated SOFA and SofaPython3 repos.

**Comment by kanta-lee** [comment]
Thanks a lot. I will try to install it from the beginning as some new error shows up when I recompile CMake.

**Comment by kanta-lee** [comment]
When I tried to run the command to test the installation ```python3 sofa_env/scenes/controllable_object_example/controllable_env.py```, I received an Import Error.
<img width="1440" alt="image" src="https://github.com/ScheiklP/sofa_zoo/assets/140193594/6c60d408-397b-4ddf-aee2-a4f26a1fa868">
\
I have asked one of the cluster admin to install the dependencies using sudo (because I have no access) `sudo apt -y install libtinyxml2-dev`, and `libtinyxml2.so.9` is installed. He has tried to find an update version of it but he could not find `libtinyxml2.so.10`. Do you anyway to solve this problem? Thank you in advance!

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet ,
no, sorry, I also just installed `libtinyxml2-dev`
https://www.sofa-framework.org/community/doc/getting-started/build/linux/#:~:text=tinyXML2,install%20libtinyxml2%2Ddev

**Comment by ScheiklP** [comment]
Hi @KantaphatLeelakunwet,
Were you able to resolve the issue?
