### ISSUE TITLE
not able to record videos

### ISSUE THREAD

**Issue by saketh2002** [ScheiklP/sofa_zoo#14]
I have pulled the latest repos of sofa_env and sofa_zoo, I previously got a Env does not have an observation type error, but then I hardcoded it in sb3 setup. The model seems to be training, but the videos arent getting recorded , and when I changed it rendermode.human, I was getting envs as seperate images instead of getting them in the same image like before. Attaching a screenshot for your reference
![Capture](https://github.com/user-attachments/assets/8e7054e5-308a-46c7-8608-c0d1ce47addf)

**Comment by Grizemc** [comment]
我想请问，lap_gym这个项目可以导出仿真的三维形变信息吗

**Comment by ScheiklP** [comment]
Hi @saketh2002 ,
Sorry for the late reply.

Sadly, I cannot reproduce your issue. I just set up sofa_env and sofa_zoo on a new system with Ubuntu 24.04, ran a training, and everything works fine.

```
-----------------------------
| time/              |      |
|    fps             | 384  |
|    iterations      | 1    |
|    time_elapsed    | 2    |
|    total_timesteps | 1024 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 480          |
|    iterations           | 2            |
|    time_elapsed         | 4            |
|    total_timesteps      | 2048         |
| train/                  |              |
|    approx_kl            | 0.0021359562 |
|    clip_fraction        | 0.0396       |
|    clip_range           | 0.1          |
|    clip_range_vf        | 0.2          |
|    entropy_loss         | -4.26        |
|    explained_variance   | 0.0010178685 |
|    learning_rate        | 0.00025      |
|    loss                 | 0.938        |
|    n_updates            | 4            |
|    policy_gradient_loss | -0.00245     |
|    std                  | 1            |
|    value_loss           | 2.19         |
------------------------------------------
Saving video to /home/paul/Repositories/sofa_zoo/sofa_zoo/envs/reach/runs/videos/rl-video-step-0-to-step-300.mp4
Moviepy - Building video /home/paul/Repositories/sofa_zoo/sofa_zoo/envs/reach/runs/videos/rl-video-step-0-to-step-300.mp4.
Moviepy - Writing video /home/paul/Repositories/sofa_zoo/sofa_zoo/envs/reach/runs/videos/rl-video-step-0-to-step-300.mp4

Moviepy - Done !                                                                                                                                                               
Moviepy - video ready /home/paul/Repositories/sofa_zoo/sofa_zoo/envs/reach/runs/videos/rl-video-step-0-to-step-300.mp4
```

Are you also on a Linux system?

Cheers,
Paul

**Comment by saketh2002** [comment]
I am currently using 20.04 LTS system, with sofa 23.06

**Comment by Grizemc** [comment]
> 我目前使用的是 20.04 LTS 系统，带有 sofa 23.06

1.May I ask if you can reproduce the script for gras_lift_touch_denv in sofa_env? I will report an error:
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::executeVisitorTopDown(sofa::simulation::Visitor*,  std::__cxx11::list<sofa::simulation::graph::DAGNode*, std::allocator<sofa::simulation::graph::DAGNode*> >&, std::map<sofa::simulation::graph::DAGNode*, sofa::simulation::graph::DAGNode::StatusStruct, std::less<sofa::simulation::graph::DAGNode*>, std::allocator<std::pair<sofa::simulation::graph::DAGNode* const, sofa::simulation::graph::DAGNode::StatusStruct> > >&, sofa::simulation::graph::DAGNode*)
sofa::simulation::graph::DAGNode::doExecuteVisitor(sofa::simulation::Visitor*, bool)
sofa::simulation::node::reset(sofa::simulation::Node*)
_PyObject_MakeTpCall
_PyEval_EvalFrameDefault
_PyEval_EvalFrameDefault
_PyFunction_Vectorcall
_PyEval_EvalFrameDefault
PyEval_EvalCode
_PyRun_SimpleFileObject
_PyRun_AnyFileObject
Py_RunMain
Py_BytesMain
__libc_start_main
Duan error (core has been dumped)
2.Meanwhile,  I followed the sofa_godot tutorial, but encountered the following error while loading and compiling in the plugin:
[INFO] [GUIManager] Registered qt as a GUI.
[INFO] [PluginManager] Loaded plugin: /home/grize/sofa/build/install/lib/libSofa. GUI.Qt.so
[INFO] [PluginManager] Loaded plugin: /home/grize/sofa/build/install/plugins/MultiThreading/lib/libMultiThreading.so
[INFO] [PluginManager] Loaded plugin: /home/grize/sofa/build/install/plugins/Sofa. Metis/lib/libSofa.Metis.so
[INFO] [PluginManager] 70 plugins have been loaded from /home/grize/sofa/build/install/lib/plugin_list.conf
[INFO] [GUIManager] lastUsedGUI.ini not found;  using default GUI.
[WARNING] [Qt] Could not find the Qt platform plugin "xcb" in ""

**Comment by ScheiklP** [comment]
Hmmm interesting.
First of all, definitely set the render mode to headless (so no windows pop up) and make sure that `render=True` in the setup (https://github.com/ScheiklP/sofa_zoo/blob/main/sofa_zoo/common/sb3_setup.py#L65), so that the correct callback (https://github.com/ScheiklP/sofa_zoo/blob/main/sofa_zoo/common/sb3_setup.py#L157) is added.

**Comment by saketh2002** [comment]
hey @ScheiklP , thanks for the help, it worked. I guess the problem is with ubuntu video viewer and the callback not getting added to the list, now I am able to see the videos once i upload them to a google drive. However , I do wanted to know if the RenderMode.HUMAN is depreciated ? I used to see a window popping up previously

**Comment by ScheiklP** [comment]
Hi @saketh2002 ,
RenderMode.HUMAN opens up a render window for each environment -> each subprocess in SubProcessVecEnv opens a window. That is the intended behavior.
To show a render window that tiles the observation from all the subprocesses, we use a Callback.
It seems like the default behavior in SB3 or Gymnasium has changed recently.
I just pushed a commit to fix that.
