### ISSUE TITLE
How to define success rate?

### ISSUE THREAD

**Issue by wjyustl** [ScheiklP/sofa_zoo#2]
I want to graph the "success rate" as you did with the number of "steps".
But I don't know how to define the "success rate".
Is it related to "'successful_task': True" in "model.ep_info_buffer" or "ep_successful_task_mean" in trajectory?
Hope to get your reply.

**Comment by ScheiklP** [comment]
Hi @wjyustl ,
In SB3, the information of finished episodes is indeed stored in `model.ep_info_buffer`.
Using SB3's wandb callback and the monitor wrapper, this data is automatically tracked and uploaded.

If you do not want to use wandb, you could also write a custom callback, similar to: https://github.com/ScheiklP/sofa_zoo/blob/main/sofa_zoo/common/callbacks.py#L7

Let me know, if that helps! :)

Cheers,
Paul

**Comment by wjyustl** [comment]
> Hi @wjyustl , In SB3, the information of finished episodes is indeed stored in `model.ep_info_buffer`. Using SB3's wandb callback and the monitor wrapper, this data is automatically tracked and uploaded.
> 
> If you do not want to use wandb, you could also write a custom callback, similar to: https://github.com/ScheiklP/sofa_zoo/blob/main/sofa_zoo/common/callbacks.py#L7
> 
> Let me know, if that helps! :)
> 
> Cheers, Paul



> Hi @wjyustl , In SB3, the information of finished episodes is indeed stored in `model.ep_info_buffer`. Using SB3's wandb callback and the monitor wrapper, this data is automatically tracked and uploaded.
> 
> If you do not want to use wandb, you could also write a custom callback, similar to: https://github.com/ScheiklP/sofa_zoo/blob/main/sofa_zoo/common/callbacks.py#L7
> 
> Let me know, if that helps! :)
> 
> Cheers, Paul

That's very kind of you. Thank you very much.
It helps me a lot as a beginner.
