### ISSUE TITLE
A problem with the ppo.py runtime.

### ISSUE THREAD

**Issue by wjyustl** [ScheiklP/sofa_zoo#7]
Hi, @ScheiklP 
When I run ppo.py in "rope_threading", the program breaks when "total_timesteps" reaches 50000 with the following error:
![image](https://github.com/ScheiklP/sofa_zoo/assets/129915667/335ec68d-8f0b-4a76-806a-e30877fcd9a0)
I guess the problem may have something to do with the render of Xservice.
Have you ever encountered this problem? Can you give me some advice?

**Comment by ScheiklP** [comment]
Hi @wjyustl,
no sorry, I have never seen this error before.
Could you try using a non-vectorized environment?
Sometimes errors get lost, when you have a multiprocessing setup.
You can test this by using the DummyVecEnv and setting the number of environments to 1.
